In [1]:
import numpy as np

**List Comprehension**

In [7]:
#number of squares
square_list = [x * x for x in range(101)]
print(square_list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


In [10]:
#number of squares only even numbers
square_list_even = [x * x for x in range(101) if (x*x) % 2 == 0]
print(square_list_even)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604, 10000]


**Generators**

In [52]:
def infinite_sequence():
    num = 1
    while True:
        string_meow = ''
        for i in range(num):
            string_meow = string_meow + 'meow '
        yield string_meow
        num = num * 2

In [56]:
gen = infinite_sequence()
for _ in range(4):
    print(next(gen))

meow 
meow meow 
meow meow meow meow 
meow meow meow meow meow meow meow meow 


**NumPy**

In [59]:
#Array erstellen
A = np.random.normal(0, 1, (5, 5))

In [60]:
A

array([[-0.30344183, -0.16259232,  0.12510029, -0.76368803, -1.08911498],
       [ 0.5007993 ,  0.78245335,  0.28113305,  2.19193431, -2.41230333],
       [-0.37827632, -2.17999738, -0.61243062, -0.80512409,  1.15387799],
       [ 0.71719078,  1.36671521, -2.72113699, -1.69994855, -0.72299871],
       [ 1.13094164,  0.43204095,  0.67688386,  0.35871771, -0.12241981]])

In [61]:
#replace elements
A[A > 0.09] = A[A > 0.09] ** 2 
A[A <= 0.09] = 42

In [62]:
A

array([[42.        , 42.        , 42.        , 42.        , 42.        ],
       [ 0.25079994,  0.61223324, 42.        ,  4.80457602, 42.        ],
       [42.        , 42.        , 42.        , 42.        ,  1.33143442],
       [ 0.51436262,  1.86791046, 42.        , 42.        , 42.        ],
       [ 1.27902899,  0.18665938,  0.45817176,  0.12867839, 42.        ]])

In [67]:
#print by slicing
print(A[0:5, 3])

[42.          4.80457602 42.         42.          0.12867839]
